;=========================================================================================================================
;
; Label.lsp
;
; Copyright Railcomplete AS / NO916118503, 2015-2020. All rights reserved.
; RailCOMPLETE (R) and the RailCOMPLETE logo are registered trademarks owned by Railcomplete AS.
;
; Change log:
; 2020-11-15 CLFEY Release 2021.1
;
;=========================================================================================================================

; Labels (with 1, 2 or 3 texts)

(defun C:LABEL ( / )
	(NO-BN-2D-JBTFE-ETIKETT-A-1-0-VLB-018)
	(NO-BN-2D-JBTFE-ETIKETT-A-1-0-VLT-018)
	(NO-BN-2D-JBTFE-ETIKETT-A-1-0-VRB-018)
	(NO-BN-2D-JBTFE-ETIKETT-A-1-0-VRT-018)
	(NO-BN-2D-JBTFE-ETIKETT-B-1-0-HLB-018)
	(NO-BN-2D-JBTFE-ETIKETT-B-1-0-HLT-018)
	(NO-BN-2D-JBTFE-ETIKETT-B-1-0-HRB-018)
	(NO-BN-2D-JBTFE-ETIKETT-B-1-0-HRT-018)
	(NO-BN-2D-JBTFE-ETIKETT-C-1-0-HLB-025)
	(NO-BN-2D-JBTFE-ETIKETT-C-1-0-HLT-025)
	(NO-BN-2D-JBTFE-ETIKETT-C-1-0-HRB-025)
	(NO-BN-2D-JBTFE-ETIKETT-C-1-0-HRT-025)
	(NO-BN-2D-JBTFE-ETIKETT-C-1-1-HLB-025-018)
	(NO-BN-2D-JBTFE-ETIKETT-C-1-1-HLT-025-018)
	(NO-BN-2D-JBTFE-ETIKETT-C-1-1-HRB-025-018)
	(NO-BN-2D-JBTFE-ETIKETT-C-1-1-HRT-025-018)
	(NO-BN-2D-JBTFE-ETIKETT-C-1-2-HLB-025-018)
	(NO-BN-2D-JBTFE-ETIKETT-C-1-2-HLT-025-018)
	(NO-BN-2D-JBTFE-ETIKETT-C-1-2-HRB-025-018)
	(NO-BN-2D-JBTFE-ETIKETT-C-1-2-HRT-025-018)
	(NO-BN-2D-JBTFE-ETIKETT-D-1-1-HLB-025-018)
	(NO-BN-2D-JBTFE-ETIKETT-D-1-1-HLT-025-018)
	(NO-BN-2D-JBTFE-ETIKETT-D-1-1-HRB-025-018)
	(NO-BN-2D-JBTFE-ETIKETT-D-1-1-HRT-025-018)
	(NO-BN-2D-JBTFE-ETIKETT-D-1-2-HLB-025-018)
	(NO-BN-2D-JBTFE-ETIKETT-D-1-2-HLT-025-018)
	(NO-BN-2D-JBTFE-ETIKETT-D-1-2-HRB-025-018)
	(NO-BN-2D-JBTFE-ETIKETT-D-1-2-HRT-025-018)
)
	
	
	
(defun NO-BN-2D-JBTFE-ETIKETT-A-1-0-VLB-018 ( / blockName )
	(setq blockName "NO-BN-2D-JBTFE-ETIKETT-A-1-0-VLB-018")
	(command "._LINE" "0,0" "0,10" "")
	(addAtt "T01" "T01" "T01" "-0.6,0" 1.8 90 "iso" "_BL" (+ _multipleLines_ _lockPosition_))
	(createSchematicBlockFromCurrentGraphics blockName)
	(createGeoBlockInAllPaperScalesFromBlock blockName _one_ blockName)
)

(defun NO-BN-2D-JBTFE-ETIKETT-A-1-0-VLT-018 ( / blockName )
	(setq blockName "NO-BN-2D-JBTFE-ETIKETT-A-1-0-VLT-018")
	(command "._LINE" "0,0" "0,10" "")
	(addAtt "T01" "T01" "T01" "-0.6,0" 1.8 90 "iso" "_BL" (+ _multipleLines_ _lockPosition_))
	(command "._MOVE" "_ALL" "" "Displacement" "0,-10") 
	(createSchematicBlockFromCurrentGraphics blockName)
	(createGeoBlockInAllPaperScalesFromBlock blockName _one_ blockName)
)

(defun NO-BN-2D-JBTFE-ETIKETT-A-1-0-VRB-018 ( / blockName )
	(setq blockName "NO-BN-2D-JBTFE-ETIKETT-A-1-0-VRB-018")
	(command "._LINE" "0,0" "0,10" "")
	(addAtt "T01" "T01" "T01" "-0.6,0" 1.8 90 "iso" "_BL" (+ _multipleLines_ _lockPosition_))
	(command "._ROTATE" "_ALL" "" "0,5" "180") 
	(createSchematicBlockFromCurrentGraphics blockName)
	(createGeoBlockInAllPaperScalesFromBlock blockName _one_ blockName)
)

(defun NO-BN-2D-JBTFE-ETIKETT-A-1-0-VRT-018 ( / blockName )
	(setq blockName "NO-BN-2D-JBTFE-ETIKETT-A-1-0-VRT-018")
	(command "._LINE" "0,0" "0,10" "")
	(addAtt "T01" "T01" "T01" "-0.6,0" 1.8 90 "iso" "_BL" (+ _multipleLines_ _lockPosition_))
	(command "._ROTATE" "_ALL" "" "0,5" "180")
	(command "._MOVE" "_ALL" "" "Displacement" "0,-10") 
	(createSchematicBlockFromCurrentGraphics blockName)
	(createGeoBlockInAllPaperScalesFromBlock blockName _one_ blockName)
)

(defun NO-BN-2D-JBTFE-ETIKETT-B-1-0-HLB-018 ( / blockName )
	(setq blockName "NO-BN-2D-JBTFE-ETIKETT-B-1-0-HLB-018")
	(command "._LINE" "0,0" "0,3" "-10,3" "")
	(addAtt "T01" "T01" "T01" "-10,2.4" 1.8 0 "iso" "_TL" (+ _multipleLines_ _lockPosition_))
	(createSchematicBlockFromCurrentGraphics blockName)
	(createGeoBlockInAllPaperScalesFromBlock blockName _one_ blockName)
)

(defun NO-BN-2D-JBTFE-ETIKETT-B-1-0-HLT-018 ( / blockName )
	(setq blockName "NO-BN-2D-JBTFE-ETIKETT-B-1-0-HLT-018")
	blockName
	(command "._LINE" "-10,0" "0,0" "0,3" "")
	(addAtt "T01" "T01" "T01" "-10,0.6" 1.8 0 "iso" "_BL" (+ _multipleLines_ _lockPosition_))
	(command "._MOVE" "_ALL" "" "0,0" "0,-3")
	(createSchematicBlockFromCurrentGraphics blockName)
	(createGeoBlockInAllPaperScalesFromBlock blockName _one_ blockName)
)

(defun NO-BN-2D-JBTFE-ETIKETT-B-1-0-HRB-018 ( / blockName )
	(setq blockName "NO-BN-2D-JBTFE-ETIKETT-B-1-0-HRB-018")
	(command "._LINE" "0,0" "0,3" "10,3" "")
	(addAtt "T01" "T01" "T01" "10,2.4" 1.8 0 "iso" "_TR" (+ _multipleLines_ _lockPosition_))
	(createSchematicBlockFromCurrentGraphics blockName)
	(createGeoBlockInAllPaperScalesFromBlock blockName _one_ blockName)
)

(defun NO-BN-2D-JBTFE-ETIKETT-B-1-0-HRT-018 ( / blockName )
	(setq blockName "NO-BN-2D-JBTFE-ETIKETT-B-1-0-HRT-018")
	(command "._LINE" "0,0" "0,3" "10,3" "")
	(addAtt "T01" "T01" "T01" "10,2.4" 1.8 0 "iso" "_TR" (+ _multipleLines_ _lockPosition_))
	(command "._MIRROR" "_ALL" "" "0,1.5" "1,1.5" "_YES")
	(command "._MOVE" "_ALL" "" "0,0" "0,-3")
	(createSchematicBlockFromCurrentGraphics blockName)
	(createGeoBlockInAllPaperScalesFromBlock blockName _one_ blockName)
)

(defun NO-BN-2D-JBTFE-ETIKETT-C-1-0-HLB-025 ( / blockName )
	(setq blockName "NO-BN-2D-JBTFE-ETIKETT-C-1-0-HLB-025")
	(command "._LINE" "0,3" "0,0" "-3,3" "-21,3" "")
	(addAtt "T01" "T01" "T01" "-21.5,3.75" 2.5 0 "iso" "_BL" (+ _multipleLines_ _lockPosition_))
	(createSchematicBlockFromCurrentGraphics blockName)
	(createGeoBlockInAllPaperScalesFromBlock blockName _one_ blockName)
)

(defun NO-BN-2D-JBTFE-ETIKETT-C-1-0-HLT-025 ( / blockName )
	(setq blockName "NO-BN-2D-JBTFE-ETIKETT-C-1-0-HLT-025")
	(command "._LINE" "0,-3" "0,0" "-3,-3" "-21,-3" "")
	(addAtt "T01" "T01" "T01" "-21.5,-2.25" 2.5 0 "iso" "_BL" (+ _multipleLines_ _lockPosition_))
	(createSchematicBlockFromCurrentGraphics blockName)
	(createGeoBlockInAllPaperScalesFromBlock blockName _one_ blockName)
)

(defun NO-BN-2D-JBTFE-ETIKETT-C-1-0-HRB-025 ( / blockName )
	(setq blockName "NO-BN-2D-JBTFE-ETIKETT-C-1-0-HRB-025")
	(command "._LINE" "0,3" "0,0" "3,3" "21,3" "")
	(addAtt "T01" "T01" "T01" "21.5,3.75" 2.5 0 "iso" "_BR" (+ _multipleLines_ _lockPosition_))
	(createSchematicBlockFromCurrentGraphics blockName)
	(createGeoBlockInAllPaperScalesFromBlock blockName _one_ blockName)
)

(defun NO-BN-2D-JBTFE-ETIKETT-C-1-0-HRT-025 ( / blockName )
	(setq blockName "NO-BN-2D-JBTFE-ETIKETT-C-1-0-HRT-025")
	(command "._LINE" "0,-3" "0,0" "3,-3" "21,-3" "")
	(addAtt "T01" "T01" "T01" "21.5,-2.25" 2.5 0 "iso" "_BR" (+ _multipleLines_ _lockPosition_))
	(createSchematicBlockFromCurrentGraphics blockName)
	(createGeoBlockInAllPaperScalesFromBlock blockName _one_ blockName)
)

(defun NO-BN-2D-JBTFE-ETIKETT-C-1-1-HLB-025-018 ( / blockName )
	(setq blockName "NO-BN-2D-JBTFE-ETIKETT-C-1-1-HLB-025-018")
	(command "._LINE" "0,3" "0,0" "-3,3" "-21,3" "")
	(addAtt "T01" "T01" "T01" "-12.5,3.75" 2.5 0 "iso" "_BC" (+ _multipleLines_ _lockPosition_))
	(addAtt "T02" "T02" "T02" "-12.5,2.4" 1.8 0 "iso" "_TC" (+ _multipleLines_ _lockPosition_))
	(createSchematicBlockFromCurrentGraphics blockName)
	(createGeoBlockInAllPaperScalesFromBlock blockName _one_ blockName)
)

(defun NO-BN-2D-JBTFE-ETIKETT-C-1-1-HLT-025-018 ( / blockName )
	(setq blockName "NO-BN-2D-JBTFE-ETIKETT-C-1-1-HLT-025-018")
	(command "._LINE" "0,0" "0,3" "-3,0" "-21,0" "")
	(addAtt "T01" "T01" "T01" "-12.5,0.75" 2.5 0 "iso" "_BC" (+ _multipleLines_ _lockPosition_))
	(addAtt "T02" "T02" "T02" "-12.5,-0.6" 1.8 0 "iso" "_TC" (+ _multipleLines_ _lockPosition_))
	(command "._MOVE" "_ALL" "" "0,0" "0,-3")
	(createSchematicBlockFromCurrentGraphics blockName)
	(createGeoBlockInAllPaperScalesFromBlock blockName _one_ blockName)
)

(defun NO-BN-2D-JBTFE-ETIKETT-C-1-1-HRB-025-018 ( / blockName )
	(setq blockName "NO-BN-2D-JBTFE-ETIKETT-C-1-1-HRB-025-018")
	(command "._LINE" "0,3" "0,0" "3,3" "21,3" "")
	(addAtt "T01" "T01" "T01" "12.5,3.75" 2.5 0 "iso" "_BC" (+ _multipleLines_ _lockPosition_))
	(addAtt "T02" "T02" "T02" "12.5,2.4" 1.8 0 "iso" "_TC" (+ _multipleLines_ _lockPosition_))
	(createSchematicBlockFromCurrentGraphics blockName)
	(createGeoBlockInAllPaperScalesFromBlock blockName _one_ blockName)
)

(defun NO-BN-2D-JBTFE-ETIKETT-C-1-1-HRT-025-018 ( / blockName )
	(setq blockName "NO-BN-2D-JBTFE-ETIKETT-C-1-1-HRT-025-018")
	(command "._LINE" "0,0" "0,3" "3,0" "21,0" "")
	(addAtt "T01" "T01" "T01" "12.5,0.75" 2.5 0 "iso" "_BC" (+ _multipleLines_ _lockPosition_))
	(addAtt "T02" "T02" "T02" "12.5,-0.6" 1.8 0 "iso" "_TC" (+ _multipleLines_ _lockPosition_))
	(command "._MOVE" "_ALL" "" "0,0" "0,-3")
	(createSchematicBlockFromCurrentGraphics blockName)
	(createGeoBlockInAllPaperScalesFromBlock blockName _one_ blockName)
)

(defun NO-BN-2D-JBTFE-ETIKETT-C-1-2-HLB-025-018 ( / blockName )
  (setq blockName "NO-BN-2D-JBTFE-ETIKETT-C-1-2-HLB-025-018")
	(command "._LINE" "0,3" "0,0" "-3,3" "-21,3" "")
	(addAtt "T01" "T01" "T01" "-12.5,3.75" 2.5 0 "iso" "_BC" (+ _multipleLines_ _lockPosition_))
	(addAtt "T02" "T02" "T02" "-12.5,2.4" 1.8 0 "iso" "_TC" (+ _multipleLines_ _lockPosition_))
	(addAtt "T03" "T03" "T03" "-12.5,0.4" 1.8 0 "iso" "_TC" (+ _multipleLines_ _lockPosition_))
	(createSchematicBlockFromCurrentGraphics blockName)
	(createGeoBlockInAllPaperScalesFromBlock blockName _one_ blockName)
)

(defun NO-BN-2D-JBTFE-ETIKETT-C-1-2-HLT-025-018 ( / blockName )
	(setq blockName "NO-BN-2D-JBTFE-ETIKETT-C-1-2-HLT-025-018")
	(command "._LINE" "0,0" "0,3" "-3,0" "-21,0" "")
	(addAtt "T01" "T01" "T01" "-12.5,0,75" 2.5 0 "iso" "_BC" (+ _multipleLines_ _lockPosition_))
	(addAtt "T02" "T02" "T02" "-12.5,-0.6" 1.8 0 "iso" "_TC" (+ _multipleLines_ _lockPosition_))
	(addAtt "T03" "T03" "T03" "-12.5,-2.6" 1.8 0 "iso" "_TC" (+ _multipleLines_ _lockPosition_))
	(command "._MOVE" "_ALL" "" "0,0" "0,-3")
	(createSchematicBlockFromCurrentGraphics blockName)
	(createGeoBlockInAllPaperScalesFromBlock blockName _one_ blockName)
)

(defun NO-BN-2D-JBTFE-ETIKETT-C-1-2-HRB-025-018 ( / blockName )
	(setq blockName "NO-BN-2D-JBTFE-ETIKETT-C-1-2-HRB-025-018")
	(command "._LINE" "0,0" "0,-3" "3,0" "21,0" "")
	(addAtt "T01" "T01" "T01" "12.5,0.75" 2.5 0 "iso" "_BC" (+ _multipleLines_ _lockPosition_))
	(addAtt "T02" "T02" "T02" "12.5,-0.6" 1.8 0 "iso" "_TC" (+ _multipleLines_ _lockPosition_))
	(addAtt "T03" "T03" "T03" "12.5,-2.6" 1.8 0 "iso" "_TC" (+ _multipleLines_ _lockPosition_))
	(createSchematicBlockFromCurrentGraphics blockName)
	(createGeoBlockInAllPaperScalesFromBlock blockName _one_ blockName)
)

(defun NO-BN-2D-JBTFE-ETIKETT-C-1-2-HRT-025-018 ( / blockName )
	(setq blockName "NO-BN-2D-JBTFE-ETIKETT-C-1-2-HRT-025-018")
	(command "._LINE" "0,0" "0,3" "3,0" "21,0" "")
	(addAtt "T01" "T01" "T01" "12.5,0.75" 2.5 0 "iso" "_BC" (+ _multipleLines_ _lockPosition_))
	(addAtt "T02" "T02" "T02" "12.5,-0.6" 1.8 0 "iso" "_TC" (+ _multipleLines_ _lockPosition_))
	(addAtt "T03" "T03" "T03" "12.5,-2.6" 1.8 0 "iso" "_TC" (+ _multipleLines_ _lockPosition_))
	(command "._MOVE" "_ALL" "" "0,0" "0,-3")
	(createSchematicBlockFromCurrentGraphics blockName)
	(createGeoBlockInAllPaperScalesFromBlock blockName _one_ blockName)
)

(defun NO-BN-2D-JBTFE-ETIKETT-D-1-1-HLB-025-018 ( / blockName )
	(setq blockName "NO-BN-2D-JBTFE-ETIKETT-D-1-1-HLB-025-018")
	(command "._LINE" "0,6" "0,0" "")
	(command "._LINE" "0,1.5" "-3,4.5" "-21,4.5" "")
	(addAtt "T01" "T01" "T01" "-12.5,5.25" 2.5 0 "iso" "_BC" (+ _multipleLines_ _lockPosition_))
	(addAtt "T02" "T02" "T02" "-12.5,3.9" 1.8 0 "iso" "_TC" (+ _multipleLines_ _lockPosition_))
	(createSchematicBlockFromCurrentGraphics blockName)
	(createGeoBlockInAllPaperScalesFromBlock blockName _one_ blockName)
)

(defun NO-BN-2D-JBTFE-ETIKETT-D-1-1-HLT-025-018 ( / blockName )
	(setq blockName "NO-BN-2D-JBTFE-ETIKETT-D-1-1-HLT-025-018")
	(command "._LINE" "0,6" "0,0" "")
	(command "._LINE" "0,4.5" "-3,1.5" "-21,1.5" "")
	(addAtt "T01" "T01" "T01" "-12.5,2.25" 2.5 0 "iso" "_BC" (+ _multipleLines_ _lockPosition_))
	(addAtt "T02" "T02" "T02" "-12.5,0.9" 1.8 0 "iso" "_TC" (+ _multipleLines_ _lockPosition_))
	(command "._MOVE" "_ALL" "" "0,0" "0,-6")
	(createSchematicBlockFromCurrentGraphics blockName)
	(createGeoBlockInAllPaperScalesFromBlock blockName _one_ blockName)
)

(defun NO-BN-2D-JBTFE-ETIKETT-D-1-1-HRB-025-018 ( / blockName )
	(setq blockName "NO-BN-2D-JBTFE-ETIKETT-D-1-1-HRB-025-018")
	(command "._LINE" "0,6" "0,0" "")
	(command "._LINE" "0,1.5" "3,4.5" "21,4.5" "")
	(addAtt "T01" "T01" "T01" "12.5,5.25" 2.5 0 "iso" "_BC" (+ _multipleLines_ _lockPosition_))
	(addAtt "T02" "T02" "T02" "12.5,3.9" 1.8 0 "iso" "_TC" (+ _multipleLines_ _lockPosition_))
	(createSchematicBlockFromCurrentGraphics blockName)
	(createGeoBlockInAllPaperScalesFromBlock blockName _one_ blockName)
)

(defun NO-BN-2D-JBTFE-ETIKETT-D-1-1-HRT-025-018 ( / blockName )
	(setq blockName "NO-BN-2D-JBTFE-ETIKETT-D-1-1-HRT-025-018")
	(command "._LINE" "0,6" "0,0" "")
	(command "._LINE" "0,4.5" "3,1.5" "21,1.5" "")
	(addAtt "T01" "T01" "T01" "12.5,2.25" 2.5 0 "iso" "_BC" (+ _multipleLines_ _lockPosition_))
	(addAtt "T02" "T02" "T02" "12.5,0.9" 1.8 0 "iso" "_TC" (+ _multipleLines_ _lockPosition_))
	(command "._MOVE" "_ALL" "" "0,0" "0,-6")
	(createSchematicBlockFromCurrentGraphics blockName)
	(createGeoBlockInAllPaperScalesFromBlock blockName _one_ blockName)
)

(defun NO-BN-2D-JBTFE-ETIKETT-D-1-2-HLB-025-018 ( / blockName )
	(setq blockName "NO-BN-2D-JBTFE-ETIKETT-D-1-2-HLB-025-018")
	(command "._LINE" "0,6" "0,0" "")
	(command "._LINE" "0,1.5" "-3,4.5" "-21,4.5" "")
	(addAtt "T01" "T01" "T01" "-12.5,5.25" 2.5 0 "iso" "_BC" (+ _multipleLines_ _lockPosition_))
	(addAtt "T02" "T02" "T02" "-12.5,3.9" 1.8 0 "iso" "_TC" (+ _multipleLines_ _lockPosition_))
	(addAtt "T03" "T03" "T03" "-12.5,1.4" 1.8 0 "iso" "_TC" (+ _multipleLines_ _lockPosition_))
	(createSchematicBlockFromCurrentGraphics blockName)
	(createGeoBlockInAllPaperScalesFromBlock blockName _one_ blockName)
)

(defun NO-BN-2D-JBTFE-ETIKETT-D-1-2-HLT-025-018 ( / blockName )
	(setq blockName "NO-BN-2D-JBTFE-ETIKETT-D-1-2-HLT-025-018")
	(command "._LINE" "0,0" "0,-6" "")
	(command "._LINE" "0,-1.5" "-3,-4.5" "-21,-4.5" "")
	(addAtt "T01" "T01" "T01" "-12.5,-3.75" 2.5 0 "iso" "_BC" (+ _multipleLines_ _lockPosition_))
	(addAtt "T02" "T02" "T02" "-12.5,-5.1" 1.8 0 "iso" "_TC" (+ _multipleLines_ _lockPosition_))
	(addAtt "T03" "T03" "T03" "-12.5,-7.6" 1.8 0 "iso" "_TC" (+ _multipleLines_ _lockPosition_))
	(createSchematicBlockFromCurrentGraphics blockName)
	(createGeoBlockInAllPaperScalesFromBlock blockName _one_ blockName)
)

(defun NO-BN-2D-JBTFE-ETIKETT-D-1-2-HRB-025-018 ( / blockName )
	(setq blockName "NO-BN-2D-JBTFE-ETIKETT-D-1-2-HRB-025-018")
	(command "._LINE" "0,6" "0,0" "")
	(command "._LINE" "0,1.5" "3,4.5" "21,4.5" "")
	(addAtt "T01" "T01" "T01" "12.5,5.25" 2.5 0 "iso" "_BC" (+ _multipleLines_ _lockPosition_))
	(addAtt "T02" "T02" "T02" "12.5,3.9" 1.8 0 "iso" "_TC" (+ _multipleLines_ _lockPosition_))
	(addAtt "T03" "T03" "T03" "12.5,1.4" 1.8 0 "iso" "_TC" (+ _multipleLines_ _lockPosition_))
	(createSchematicBlockFromCurrentGraphics blockName)
	(createGeoBlockInAllPaperScalesFromBlock blockName _one_ blockName)
)

(defun NO-BN-2D-JBTFE-ETIKETT-D-1-2-HRT-025-018 ( / blockName )
	(setq blockName "NO-BN-2D-JBTFE-ETIKETT-D-1-2-HRT-025-018")
	(command "._LINE" "0,0" "0,-6" "")
	(command "._LINE" "0,-1.5" "3,-4.5" "21,-4.5" "")
	(addAtt "T01" "T01" "T01" "12.5,-3.75" 2.5 0 "iso" "_BC" (+ _multipleLines_ _lockPosition_))
	(addAtt "T02" "T02" "T02" "12.5,-5.1" 1.8 0 "iso" "_TC" (+ _multipleLines_ _lockPosition_))
	(addAtt "T03" "T03" "T03" "12.5,-7.6" 1.8 0 "iso" "_TC" (+ _multipleLines_ _lockPosition_))
	(createSchematicBlockFromCurrentGraphics blockName)
	(createGeoBlockInAllPaperScalesFromBlock blockName _one_ blockName)
)
